# Generated by Django 5.2.7 on 2025-11-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='pt_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание услуги'),
        ),
    ]
